import {useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/router';
import Icon,{BrandMark} from './Icon';
export default function AppShell({children}){
 const router=useRouter();const [open,setOpen]=useState(false);
 const section=router.pathname.startsWith('/chat')?'chat':router.pathname==='/documents'?'documents':'upload';
 const nav=[['documents','Documents','/documents','library'],['upload','Upload','/','upload'],['chat','Chat','/chat','chat']];
 return <div className="app-shell"><button className={`sidebar-scrim ${open?'visible':''}`} aria-label="Close navigation" onClick={()=>setOpen(false)}/><aside className={`sidebar ${open?'open':''}`}><Link href="/documents" className="brand" onClick={()=>setOpen(false)}><BrandMark/><span><strong>DocuRAG</strong><span className="brand-description">Your documents,<br/>smarter answers</span></span></Link><nav aria-label="Main navigation">{nav.map(([id,label,href,icon])=><Link key={id} href={href} className={`nav-item ${section===id?'active':''}`} aria-current={section===id?'page':undefined} onClick={()=>setOpen(false)}><Icon name={icon}/>{label}{section===id&&<span className="nav-dot"/>}</Link>)}</nav><div className="sidebar-bottom"><div className="sidebar-art" aria-hidden="true"/><p className="sidebar-quote">“Turn your documents<br/>into knowledge.”</p><div className="profile"><span className="profile-avatar">L</span><span><strong>Local workspace</strong><small><span className="status-dot"/> On-device AI</small></span><Icon name="shield" size={17}/></div></div></aside><div className="app-main"><header className="topbar"><button className="icon-button menu-toggle" onClick={()=>setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open}><Icon name="menu"/></button><div className="topbar-breadcrumb">Workspace <span>/</span> <strong>{section==='documents'?'Documents':section==='chat'?'Document chat':'Upload'}</strong></div><div className="topbar-right"><span className="local-badge"><span className="status-dot"/> Local intelligence</span><span className="topbar-quote">Knowledge<br/><em>at your fingertips</em></span></div></header><main>{children}</main></div></div>;
}
