import {useState,useRef,useEffect} from 'react';
import {PdfIcon,BrandMark} from './Icon';
import {DocumentMeta} from './DocumentCard';
import ChatMessage from './ChatMessage';
import ChatInput from './ChatInput';
export default function ChatPanel({document,documentId,embedded=false}){
 const id=document?.id||documentId;const [messages,setMessages]=useState([]);const [pending,setPending]=useState(null);const [error,setError]=useState('');const thread=useRef(null);const request=useRef(null);
 useEffect(()=>()=>request.current?.abort(),[]);
 useEffect(()=>{if(thread.current)thread.current.scrollTop=thread.current.scrollHeight;},[messages,pending,error]);
 async function ask(question){if(pending)return false;setError('');setPending({question,time:Date.now()});const controller=new AbortController();request.current=controller;try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({documentId:id,question}),signal:controller.signal});const data=await r.json();if(!r.ok)throw new Error(data.error||'Could not answer. Please try again.');setMessages(old=>[...old,{question,questionTime:Date.now(),...data,time:Date.now()}]);return true;}catch(e){if(e.name!=='AbortError')setError(e.message);return false;}finally{setPending(null);}}
 return <section className={`chat-panel ${embedded?'embedded':''}`} aria-label="Document chat"><header className="chat-header"><PdfIcon/><div><h2 title={document?.title}>{document?.title||`Document ${id}`}</h2>{document?<DocumentMeta document={document}/>:<p className="muted">Ask questions from this document</p>}</div><span className="chat-header-dot" title="Document context selected"/></header><div className="conversation" ref={thread} aria-live="polite" aria-relevant="additions text">{!messages.length&&!pending&&<div className="chat-welcome"><BrandMark/><p className="eyebrow">YOUR DOCUMENT, UNDERSTOOD</p><h2>Let’s find the answer.</h2><p>Ask a question about this PDF.<br/>Get a grounded answer with sources you can explore.</p><div className="welcome-divider"/><span><span className="status-dot"/> Local AI · Private inference</span></div>}{messages.map((m,i)=><div key={i}><ChatMessage sender="You" message={m.question} time={m.questionTime}/><ChatMessage sender="Assistant" message={m.answer} sources={m.sources} time={m.time}/></div>)}{pending&&<><ChatMessage sender="You" message={pending.question} time={pending.time}/><div className="message-row assistant"><BrandMark small/><div className="thinking" role="status"><span className="thinking-dots"><i/><i/><i/></span>Finding answers in your document</div></div></>}{error&&<p className="alert error" role="alert">{error}</p>}</div><ChatInput onSend={ask} loading={!!pending} disabled={!Number.isSafeInteger(id)||id<1}/></section>;
}
