import {useState} from 'react';
import Link from 'next/link';
import PdfUploader from './PdfUploader';
import Icon from './Icon';
const stages=['Extracting text','Creating chunks','Generating embeddings','Saving document'];
export default function UploadZone({onComplete}){
 const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState(null);
 async function upload(file){if(loading)return;setError('');setResult(null);if(!/\.pdf$/i.test(file.name)){setError('Please choose a PDF file.');return;}if(!file.size||file.size>4_000_000){setError('Choose a non-empty PDF no larger than 4 MB.');return;}setLoading(true);try{const form=new FormData();form.append('file',file);const r=await fetch('/api/upload',{method:'POST',body:form});const data=await r.json();if(!r.ok)throw new Error(data.error||'Upload failed. Please try again.');setResult(data);onComplete?.(data);}catch(e){setError(e.message||'Upload failed. Check your connection and try again.');}finally{setLoading(false);}}
 return <section className="upload-zone" aria-label="Upload a PDF"><PdfUploader onUpload={upload} disabled={loading}/>{loading&&<div className="processing-panel" role="status"><div className="processing-title"><span className="spinner"/><strong>Turning your PDF into knowledge</strong></div><p>The pipeline below is running. We’ll confirm when indexing is complete.</p><div className="processing-stages">{stages.map((s,i)=><span key={s}><b>{i+1}</b>{s}</span>)}</div><div className="indeterminate-track"><span/></div></div>}{error&&<p className="alert error" role="alert">{error}</p>}{result&&<div className="upload-success" role="status"><span className="success-icon"><Icon name="check"/></span><div><strong>Your document is ready</strong><p className="success-filename">{result.filename}</p><small>{result.pageCount} pages · {result.chunkCount} chunks indexed</small>{result.warning&&<p>{result.warning}</p>}</div><Link className="button primary compact" href={`/brief/${result.documentId}`}>Review <Icon name="arrow" size={16}/></Link></div>}</section>;
}
