import {useState,useMemo,useRef} from 'react';
import useDocuments from '../hooks/useDocuments';
import PageHeader from '../components/PageHeader';
import DocumentCard from '../components/DocumentCard';
import UploadZone from '../components/UploadZone';
import ChatPanel from '../components/ChatPanel';
import Icon from '../components/Icon';
import EmptyState,{LoadingIndicator} from '../components/EmptyState';
export default function DocumentsPage(){
 const {documents,error,refresh}=useDocuments();const [search,setSearch]=useState('');const [sort,setSort]=useState('newest');const upload=useRef(null);
 const filtered=useMemo(()=>[...(documents||[])].filter(d=>d.title.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='name'?a.title.localeCompare(b.title):sort==='oldest'?new Date(a.createdAt)-new Date(b.createdAt):new Date(b.createdAt)-new Date(a.createdAt)),[documents,search,sort]);
 const active=documents?.[0];
 return <div className="library-layout"><section className="library-column"><PageHeader eyebrow="DOCUMENTS" title="Your document library" description="Upload PDFs and chat with them using AI." action={<button className="button primary" onClick={()=>{upload.current?.scrollIntoView({behavior:'smooth',block:'center'});upload.current?.querySelector('button')?.focus({preventScroll:true});}}><Icon name="plus" size={19}/>Upload PDF</button>}/><div className="library-toolbar"><label className="search-field"><Icon name="search" size={18}/><span className="sr-only">Search documents</span><input placeholder="Search documents..." value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="sort-field"><span className="sr-only">Sort documents</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="name">Name A–Z</option></select><Icon name="chevron" size={15}/></label></div>{error&&<div className="alert error" role="alert">{error} <button className="text-button" onClick={refresh}>Retry</button></div>}{!documents&&!error&&<LoadingIndicator text="Loading your library..."/>}<div className="document-list">{filtered.map(d=><DocumentCard key={d.id} document={d} selected={d.id===active?.id}/>)}{documents&&!filtered.length&&<EmptyState title={search?'No matching documents':'A little knowledge goes a long way.'} description={search?'Try a different filename.':'Upload your first PDF to start the conversation.'}/>}</div><div ref={upload} className="library-upload"><UploadZone onComplete={refresh}/></div><p className="library-footnote"><Icon name="shield" size={14}/>Local AI. Answers grounded in your documents.</p></section><aside className="library-chat">{active?<ChatPanel key={active.id} document={active} embedded/>:<div className="chat-panel preview-empty"><EmptyState title="A conversation waiting to happen" description="Once you upload a document, its chat will appear here." icon="chat"/></div>}</aside></div>;
}
